### ISSUE TITLE
New version of ii2-geoip in Packagist

### ISSUE THREAD

**Issue by davicrystal** [lysenkobv/yii2-geoip#4]
Will you publish the new version 1.0.1 in Packagist? ( https://packagist.org/packages/lysenkobv/yii2-geoip )

Tks

**Comment by lysenkobv** [comment]
@davicrystal Hi! Something wrong was with packagist settings, I fixed integration and updated `composer.json` as well. So it seems like it works now, but I had to increase version to 1.0.3 without any new features.
