### ISSUE TITLE
 What is the difference between this database and GeoLite City Edition?

### ISSUE THREAD

**Issue by Sergwizard** [lysenkobv/yii2-geoip#7]
Hello! My question point is not about bugs. This extention works perfect for me. I want ask about data base an extention.

If I use php function geoip_record_by_name I`ll get some result like in this extention, or  there are differences about?

**Comment by lysenkobv** [comment]
`geoip_record_by_name` is the function from external PECL extension, thus `yii2-geoip` and PECL extensions are both external libs. The question is what you personally prefer to use.
